# group_vars/all.yml
---
prometheus_image: "prom/prometheus"
prometheus_version: "v3.9.1"

cadvisor_image: "gcr.io/cadvisor/cadvisor"
cadvisor_version: "v0.55.1"

jenkins_image: "jenkins/jenkins"
jenkins_version: "2.550"
jenkins_admin_user: "admin"
jenkins_url: "https://shadowlands.tail252efc.ts.net"
github_username: "bmcivor"
jenkins_repos:
  - vertex-block

minecraft_bedrock_image: "itzg/minecraft-bedrock-server"
minecraft_bedrock_version: "2026.2.0"

registry_image: "registry"
registry_version: "2"
