---
- name: Create jenkins directory
  ansible.builtin.file:
    path: /opt/jenkins
    state: directory
    owner: "{{ ansible_user }}"
    group: docker
    mode: '0755'

- name: Get Docker group GID
  ansible.builtin.command: getent group docker
  register: docker_group_info
  changed_when: false

- name: Set Docker GID fact
  ansible.builtin.set_fact:
    docker_gid: "{{ docker_group_info.stdout.split(':')[2] }}"

- name: Copy plugins.txt
  ansible.builtin.copy:
    src: plugins.txt
    dest: /opt/jenkins/plugins.txt
    owner: "{{ ansible_user }}"
    group: docker
    mode: '0644'

- name: Copy Dockerfile
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: /opt/jenkins/Dockerfile
    owner: "{{ ansible_user }}"
    group: docker
    mode: '0644'

- name: Build Jenkins
  ansible.builtin.command:
    cmd: docker build -t jenkins-custom:{{ jenkins_version }} .
    chdir: /opt/jenkins

- name: Copy JCasC configuration
  ansible.builtin.template:
    src: jenkins-casc.yaml.j2
    dest: /opt/jenkins/jenkins-casc.yaml
    owner: "{{ ansible_user }}"
    group: docker
    mode: '0644'

- name: Create .env file for secrets
  ansible.builtin.template:
    src: env.j2
    dest: /opt/jenkins/.env
    owner: "{{ ansible_user }}"
    group: docker
    mode: '0600'

- name: Copy docker-compose.yaml
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: /opt/jenkins/docker-compose.yaml
    owner: "{{ ansible_user }}"
    group: docker
    mode: '0644'

- name: Start Jenkins
  ansible.builtin.command:
    cmd: docker compose up -d --force-recreate
    chdir: /opt/jenkins
