---
- name: Minecraft Bedrock Server Management
  hosts: labserver
  become: true
  vars:
    minecraft_bedrock_destroy: false
  tasks:
    - name: Destroy Minecraft Bedrock Server
      ansible.builtin.command:
        cmd: docker compose down -v
        chdir: /opt/minecraft-bedrock
        removes: /opt/minecraft-bedrock/docker-compose.yaml
      when: minecraft_bedrock_destroy | bool
  roles:
    - role: minecraft-bedrock
      when: not (minecraft_bedrock_destroy | bool)
